spring:
  datasource:
    url: "jdbc:postgresql://identity-service:5434/crm"
    username: myuser
    password: mypassword
eureka:
  client:
    service-url:
      defaultZone: "http://discovery-server-app:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true
