spring:
  profiles:
    active: dev
  application:
    name: customer-service
    jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        ddl-auto: update
      show-sql: true
server:
  port: 8081

