spring:
  profiles:
    active: dev
  application:
    name: customer-service
  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
    showSql: true
    hibernate:
      ddlAuto: update
server:
  port: 8081

