datasource:
  url: jdbc:mysql://customer-service:3307/mydatabase?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  username: myuser
  password: mypassword
  driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: "http://discovery-server-app:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true