spring:
  datasource:
    url: "jdbc:postgresql://localhost:5433/crm"
    username: myuser
    password: mypassword
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true
