eureka:
  instance:
    hostname: "discovery-server-app"
  client:
    serviceUrl:
      defaultZone: "http://discovery-server-app:8888/eureka/"
    register-with-eureka: false
    fetch-registry: false
