spring:
  data:
    mongodb:
      uri: mongodb://mongouser:mongopassword@localhost:27019/crm?authSource=admin
#      username: mongouser
#      password: mongopassword
#      authentication-database: admin
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true
