spring:
  data:
    mongodb:
      uri: mongodb://localhost:27018/crm
      username: mongouser
      password: mongopassword
      authentication-database: admin

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true
